version: "3"
services:
  db_postgresql:
    image: postgres:latest
    container_name: ms_broker_db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DATABASE_NAMEDB}
    ports:
    - 5432:5432

  api_server:
    image: ms_broker
    container_name: ms_broker_api-server
    ports:
      - 3000:3000
    depends_on:
      - db_postgresql

